### ISSUE TITLE
codes problem

### ISSUE THREAD

**Issue by zqcrystal325** [verena-zuber/demo_AMD#1]
Hi, guys
When I run with the codes:

amd_nmr_input=new("mvMRInput", betaX = as.matrix(betaX_ivw), betaY = as.matrix(amd_beta_ivw), snps=rs, exposure=rf, outcome = "amd")

and I got the error bellow:
Error in getClass(Class, where = topenv(parent.frame())) : “mvMRInput” is not a defined class

Do you know how to solve this?
Thanks

**Comment by zqcrystal325** [comment]
Never mind, I got this!

**Comment by verena-zuber** [comment]
So sorry for the late reply. The class is defined as 

setClass("mvMRInput",
         representation(betaX = "matrix",
                        betaY = "matrix",
                        betaXse = "matrix",
                        betaYse = "matrix",
                        exposure = "character",
                        outcome = "character",
                        snps = "character",
                        effect_allele = "character",
                        other_allele  = "character",
                        eaf           = "numeric",                        
			correlation = "matrix")
)

Please let us know if you have any other issues.
