### ISSUE TITLE
Genetic correlation between metabolites

### ISSUE THREAD

**Issue by rtabassu** [verena-zuber/demo_AMD#2]
Hi, you suggested that metabolites with high genetic correlation based on genetic instruments should be excluded. Could you suggest a method to calculate the genetic correlation based on a few selected variants? Thanks!

**Comment by verena-zuber** [comment]
Thanks rtabassu, the genetic correlation is simply the correlation between the genetic associations (or beta's) of the risk factors measured on the SNPs you use as instrumental variables. If your input matrix is betaX (dimension n (#SNPs) x p (#risk factors)) you can compute the correlation matrix (dimension pxp) using cor and plot using the library ggplot2 and reshape:

cor_beta = cor(betaX)
dim(cor_beta)
melted_cormat = melt(cor_beta)

print(
ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Correlation \n between betas") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1))+
 coord_fixed()+
 theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank()
 )
)

**Comment by rtabassu** [comment]
Hi Verena,

Thanks for the prompt reply. Yes, I realized so and found the code in one of your scripts in github.

Best,

Rubina

Rubina Tabassum, PhD
Postdoctoral Researcher
Institute for Molecular Medicine Finland (FIMM)
University of Helsinki, Finland

**Comment by verena-zuber** [comment]
Dear Rubina, great happy to hear this, I am closing the issue now.
But please do get in touch if you have any other question or if you have any comments or feedback on the code. Hope to make this into a proper R-package soon. 

Thanks for your interest, Verena
